clusterRole:
  create: true
  name: "testing-clusterrole"
  rules:
    - apiGroups:
      - ''
      resources:
      - 'pods'
      - 'nodes'
      verbs:
      - 'get'
      - 'list'
      - 'watch'
  clusterRoleBinding:
    name: "testing-clusterrolebinding"

agentCollector:
  enabled: true
standaloneCollector:
  enabled: false
