agentCollector:
  enabled: true
  configOverride:
    receivers:
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
    service:
      pipelines:
        metrics:
          receivers: [prometheus, hostmetrics]

standaloneCollector:
  enabled: false
