ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

agentCollector:
  enabled: true
standaloneCollector:
  enabled: false
